from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import psycopg
from psycopg.rows import dict_row

from app.config.env import load_dotenv_file
from app.data.loader import DEFAULT_RESORTS_PATH, load_resorts_from_path

DATABASE_URL_ENV_VAR = "DATABASE_URL"
DEFAULT_DATABASE_URL = (
    "postgresql://planner:planner@127.0.0.1:5432/ai_sports_travel_planner"
)


def resolve_database_url() -> str:
    load_dotenv_file()
    return os.getenv(DATABASE_URL_ENV_VAR, DEFAULT_DATABASE_URL)


def connect(
    database_url: str | os.PathLike[str] | None = None,
) -> psycopg.Connection[Any]:
    normalized_url = _normalize_database_url(database_url)
    return psycopg.connect(normalized_url, row_factory=dict_row)


def bootstrap_database(
    database_url: str | os.PathLike[str] | None = None,
    *,
    resorts_path: Path = DEFAULT_RESORTS_PATH,
) -> None:
    with connect(database_url) as connection:
        _create_schema(connection)
        _sync_resorts_from_seed(connection, resorts_path)
        _clear_legacy_seeded_conditions(connection)


def reset_database(
    database_url: str | os.PathLike[str] | None = None,
    *,
    resorts_path: Path = DEFAULT_RESORTS_PATH,
) -> None:
    with connect(database_url) as connection:
        connection.execute("DROP SCHEMA IF EXISTS public CASCADE")
        connection.execute("CREATE SCHEMA public")
        _create_schema(connection)
        _sync_resorts_from_seed(connection, resorts_path)
        _clear_legacy_seeded_conditions(connection)


def _normalize_database_url(
    database_url: str | os.PathLike[str] | None,
) -> str:
    if database_url is None:
        return resolve_database_url()
    if isinstance(database_url, os.PathLike):
        return resolve_database_url()
    if "://" not in database_url:
        return resolve_database_url()
    return database_url


def _create_schema(connection: psycopg.Connection[Any]) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS resorts (
            resort_id TEXT PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            country TEXT NOT NULL,
            region TEXT NOT NULL,
            price_level TEXT NOT NULL,
            latitude DOUBLE PRECISION NOT NULL,
            longitude DOUBLE PRECISION NOT NULL,
            base_elevation_m INTEGER NOT NULL,
            summit_elevation_m INTEGER NOT NULL,
            season_start_month INTEGER NOT NULL,
            season_end_month INTEGER NOT NULL
        );

        CREATE TABLE IF NOT EXISTS ski_areas (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            resort_id TEXT NOT NULL REFERENCES resorts(resort_id) ON DELETE CASCADE,
            ski_area_id TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            latitude DOUBLE PRECISION NOT NULL,
            longitude DOUBLE PRECISION NOT NULL,
            base_elevation_m INTEGER NOT NULL,
            summit_elevation_m INTEGER NOT NULL,
            season_start_month INTEGER NOT NULL,
            season_end_month INTEGER NOT NULL
        );

        CREATE TABLE IF NOT EXISTS stay_bases (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            resort_id TEXT NOT NULL REFERENCES resorts(resort_id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            price_range TEXT NOT NULL,
            price_min DOUBLE PRECISION NOT NULL,
            price_max DOUBLE PRECISION NOT NULL,
            quality TEXT NOT NULL,
            lift_distance TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS stay_base_skill_levels (
            stay_base_id INTEGER NOT NULL REFERENCES stay_bases(id) ON DELETE CASCADE,
            skill_level TEXT NOT NULL,
            PRIMARY KEY (stay_base_id, skill_level)
        );

        CREATE TABLE IF NOT EXISTS rentals (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            resort_id TEXT NOT NULL REFERENCES resorts(resort_id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            price_range TEXT NOT NULL,
            price_min DOUBLE PRECISION NOT NULL,
            price_max DOUBLE PRECISION NOT NULL,
            quality TEXT NOT NULL,
            lift_distance TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS resort_conditions (
            resort_id TEXT PRIMARY KEY
                REFERENCES ski_areas(ski_area_id) ON DELETE CASCADE,
            resort_name TEXT NOT NULL UNIQUE,
            snow_confidence_score DOUBLE PRECISION NOT NULL,
            snow_confidence_label TEXT NOT NULL,
            availability_status TEXT NOT NULL,
            weather_summary TEXT NOT NULL,
            conditions_score DOUBLE PRECISION NOT NULL,
            updated_at TEXT,
            source TEXT
        );

        CREATE TABLE IF NOT EXISTS resort_condition_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            resort_id TEXT NOT NULL REFERENCES ski_areas(ski_area_id) ON DELETE CASCADE,
            resort_name TEXT NOT NULL,
            observed_month INTEGER NOT NULL,
            observed_at TEXT NOT NULL,
            snow_confidence_score DOUBLE PRECISION NOT NULL,
            snow_confidence_label TEXT NOT NULL,
            availability_status TEXT NOT NULL,
            weather_summary TEXT NOT NULL,
            conditions_score DOUBLE PRECISION NOT NULL,
            source TEXT,
            UNIQUE(resort_id, observed_at)
        );

        CREATE TABLE IF NOT EXISTS llm_parse_cache (
            cache_key TEXT PRIMARY KEY,
            query_text TEXT NOT NULL,
            model TEXT NOT NULL,
            prompt_version TEXT NOT NULL,
            schema_version TEXT NOT NULL,
            response_json TEXT NOT NULL,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS llm_narrative_cache (
            cache_key TEXT PRIMARY KEY,
            result_signature TEXT NOT NULL,
            model TEXT NOT NULL,
            prompt_version TEXT NOT NULL,
            schema_version TEXT NOT NULL,
            response_json TEXT NOT NULL,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS outbound_booking_clicks (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TEXT NOT NULL,
            resort_id TEXT NOT NULL REFERENCES resorts(resort_id) ON DELETE CASCADE,
            selected_area_name TEXT NOT NULL,
            selected_ski_area_name TEXT,
            target_url TEXT NOT NULL,
            source_surface TEXT NOT NULL,
            request_id TEXT,
            user_agent TEXT
        );

        CREATE TABLE IF NOT EXISTS current_trip (
            singleton_id INTEGER PRIMARY KEY CHECK (singleton_id = 1),
            resort_id TEXT NOT NULL REFERENCES resorts(resort_id) ON DELETE CASCADE,
            resort_name TEXT NOT NULL,
            selected_area_name TEXT NOT NULL,
            selected_ski_area_id TEXT,
            selected_ski_area_name TEXT,
            travel_month INTEGER,
            booking_status TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_checked_at TEXT
        );
        """
    )


def _sync_resorts_from_seed(
    connection: psycopg.Connection[Any],
    resorts_path: Path,
) -> None:
    resorts = load_resorts_from_path(resorts_path)
    seeded_ids = sorted(resort.resort_id for resort in resorts)

    if seeded_ids:
        connection.execute(
            "DELETE FROM resorts WHERE NOT (resort_id = ANY(%s))",
            (seeded_ids,),
        )
    else:
        connection.execute("DELETE FROM resorts")

    for resort in resorts:
        connection.execute(
            """
            INSERT INTO resorts (
                resort_id,
                name,
                country,
                region,
                price_level,
                latitude,
                longitude,
                base_elevation_m,
                summit_elevation_m,
                season_start_month,
                season_end_month
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (resort_id) DO UPDATE SET
                name = excluded.name,
                country = excluded.country,
                region = excluded.region,
                price_level = excluded.price_level,
                latitude = excluded.latitude,
                longitude = excluded.longitude,
                base_elevation_m = excluded.base_elevation_m,
                summit_elevation_m = excluded.summit_elevation_m,
                season_start_month = excluded.season_start_month,
                season_end_month = excluded.season_end_month
            """,
            (
                resort.resort_id,
                resort.name,
                resort.country,
                resort.region,
                resort.price_level,
                resort.latitude,
                resort.longitude,
                resort.base_elevation_m,
                resort.summit_elevation_m,
                resort.season_start_month,
                resort.season_end_month,
            ),
        )

        connection.execute(
            """
            DELETE FROM stay_base_skill_levels
            WHERE stay_base_id IN (
                SELECT id FROM stay_bases WHERE resort_id = %s
            )
            """,
            (resort.resort_id,),
        )
        connection.execute(
            "DELETE FROM stay_bases WHERE resort_id = %s",
            (resort.resort_id,),
        )
        connection.execute(
            "DELETE FROM rentals WHERE resort_id = %s",
            (resort.resort_id,),
        )

        current_ski_area_ids = [ski_area.ski_area_id for ski_area in resort.ski_areas]
        for ski_area in resort.ski_areas:
            connection.execute(
                """
                INSERT INTO ski_areas (
                    resort_id,
                    ski_area_id,
                    name,
                    latitude,
                    longitude,
                    base_elevation_m,
                    summit_elevation_m,
                    season_start_month,
                    season_end_month
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (ski_area_id) DO UPDATE SET
                    resort_id = excluded.resort_id,
                    name = excluded.name,
                    latitude = excluded.latitude,
                    longitude = excluded.longitude,
                    base_elevation_m = excluded.base_elevation_m,
                    summit_elevation_m = excluded.summit_elevation_m,
                    season_start_month = excluded.season_start_month,
                    season_end_month = excluded.season_end_month
                """,
                (
                    resort.resort_id,
                    ski_area.ski_area_id,
                    ski_area.name,
                    ski_area.latitude,
                    ski_area.longitude,
                    ski_area.base_elevation_m,
                    ski_area.summit_elevation_m,
                    ski_area.season_start_month,
                    ski_area.season_end_month,
                ),
            )

        if current_ski_area_ids:
            connection.execute(
                """
                DELETE FROM ski_areas
                WHERE resort_id = %s AND NOT (ski_area_id = ANY(%s))
                """,
                (resort.resort_id, current_ski_area_ids),
            )
        else:
            connection.execute(
                "DELETE FROM ski_areas WHERE resort_id = %s",
                (resort.resort_id,),
            )

        for stay_base in resort.stay_bases:
            stay_base_row = connection.execute(
                """
                INSERT INTO stay_bases (
                    resort_id,
                    name,
                    price_range,
                    price_min,
                    price_max,
                    quality,
                    lift_distance
                ) VALUES (%s, %s, %s, %s, %s, %s, %s)
                RETURNING id
                """,
                (
                    resort.resort_id,
                    stay_base.name,
                    stay_base.price_range,
                    stay_base.price_min,
                    stay_base.price_max,
                    stay_base.quality,
                    stay_base.lift_distance,
                ),
            ).fetchone()
            assert stay_base_row is not None
            for skill_level in stay_base.supported_skill_levels:
                connection.execute(
                    """
                    INSERT INTO stay_base_skill_levels (stay_base_id, skill_level)
                    VALUES (%s, %s)
                    """,
                    (stay_base_row["id"], skill_level),
                )

        for rental in resort.rentals:
            connection.execute(
                """
                INSERT INTO rentals (
                    resort_id,
                    name,
                    price_range,
                    price_min,
                    price_max,
                    quality,
                    lift_distance
                ) VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    resort.resort_id,
                    rental.name,
                    rental.price_range,
                    rental.price_min,
                    rental.price_max,
                    rental.quality,
                    rental.lift_distance,
                ),
            )


def _clear_legacy_seeded_conditions(connection: psycopg.Connection[Any]) -> None:
    connection.execute("DELETE FROM resort_conditions WHERE source IS NULL")
