from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import psycopg
from psycopg.rows import dict_row

from app.config.env import load_dotenv_file
from app.data.loader import (
    DEFAULT_RESORTS_PATH,
    _stable_stay_base_id,
    load_resorts_from_path,
    load_terrain_domains_from_path,
    resolve_terrain_domains_path,
)

DATABASE_URL_ENV_VAR = "DATABASE_URL"
DEFAULT_DATABASE_URL = (
    "postgresql://planner:planner@127.0.0.1:5432/ai_sports_travel_planner"
)

TRAVEL_CACHE_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS travel_geocode_cache (
    normalized_origin TEXT NOT NULL,
    provider TEXT NOT NULL,
    resolved_label TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    fetched_at TEXT NOT NULL,
    PRIMARY KEY (normalized_origin, provider)
);

CREATE TABLE IF NOT EXISTS travel_route_cache (
    origin_key TEXT NOT NULL,
    destination_entity_type TEXT NOT NULL,
    destination_entity_id TEXT NOT NULL,
    destination_coord_key TEXT NOT NULL,
    mode TEXT NOT NULL,
    provider TEXT NOT NULL,
    distance_km DOUBLE PRECISION NOT NULL,
    duration_minutes INTEGER NOT NULL,
    provenance TEXT NOT NULL,
    fetched_at TEXT NOT NULL,
    PRIMARY KEY (
        origin_key,
        destination_entity_type,
        destination_entity_id,
        destination_coord_key,
        mode,
        provider
    )
);
"""


def resolve_database_url() -> str:
    load_dotenv_file()
    return os.getenv(DATABASE_URL_ENV_VAR, DEFAULT_DATABASE_URL)


def connect(
    database_url: str | None = None,
) -> psycopg.Connection[Any]:
    return psycopg.connect(database_url or resolve_database_url(), row_factory=dict_row)


def bootstrap_database(
    database_url: str | None = None,
    *,
    resorts_path: Path = DEFAULT_RESORTS_PATH,
    terrain_domains_path: Path | None = None,
) -> None:
    effective_terrain_domains_path = resolve_terrain_domains_path(
        resorts_path, terrain_domains_path
    )
    with connect(database_url) as connection:
        _create_schema(connection)
        _sync_resorts_from_seed(connection, resorts_path)
        _sync_terrain_domains_from_seed(connection, effective_terrain_domains_path)
        _clear_legacy_seeded_conditions(connection)


def reset_database(
    database_url: str | None = None,
    *,
    resorts_path: Path = DEFAULT_RESORTS_PATH,
    terrain_domains_path: Path | None = None,
) -> None:
    effective_terrain_domains_path = resolve_terrain_domains_path(
        resorts_path, terrain_domains_path
    )
    with connect(database_url) as connection:
        connection.execute("DROP SCHEMA IF EXISTS public CASCADE")
        connection.execute("CREATE SCHEMA public")
        _create_schema(connection)
        _sync_resorts_from_seed(connection, resorts_path)
        _sync_terrain_domains_from_seed(connection, effective_terrain_domains_path)
        _clear_legacy_seeded_conditions(connection)


def ensure_travel_cache_schema(database_url: str | None = None) -> None:
    with connect(database_url) as connection:
        _create_travel_cache_schema(connection)


def ensure_catalog_schema(database_url: str | None = None) -> None:
    with connect(database_url) as connection:
        _create_schema(connection)


def _create_schema(connection: psycopg.Connection[Any]) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS resorts (
            resort_id TEXT PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            country TEXT NOT NULL,
            region TEXT NOT NULL,
            price_level TEXT NOT NULL,
            latitude DOUBLE PRECISION NOT NULL,
            longitude DOUBLE PRECISION NOT NULL,
            base_elevation_m INTEGER NOT NULL,
            summit_elevation_m INTEGER NOT NULL,
            season_start_month INTEGER NOT NULL,
            season_end_month INTEGER NOT NULL,
            season_windows_json TEXT NOT NULL DEFAULT '[]',
            lift_pass_prices_json TEXT NOT NULL DEFAULT '[]',
            lift_pass_products_json TEXT NOT NULL DEFAULT '[]',
            terrain_groups_json TEXT NOT NULL DEFAULT '[]'
        );

        CREATE TABLE IF NOT EXISTS ski_areas (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            resort_id TEXT NOT NULL REFERENCES resorts(resort_id) ON DELETE CASCADE,
            ski_area_id TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            latitude DOUBLE PRECISION NOT NULL,
            longitude DOUBLE PRECISION NOT NULL,
            base_elevation_m INTEGER NOT NULL,
            summit_elevation_m INTEGER NOT NULL,
            season_start_month INTEGER NOT NULL,
            season_end_month INTEGER NOT NULL,
            season_windows_json TEXT NOT NULL DEFAULT '[]',
            total_piste_km DOUBLE PRECISION,
            total_lift_count INTEGER,
            piste_km_by_difficulty_json TEXT
        );

        CREATE TABLE IF NOT EXISTS terrain_domains (
            terrain_domain_id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            ski_area_refs_json TEXT NOT NULL,
            metric_scope TEXT NOT NULL,
            total_piste_km DOUBLE PRECISION,
            total_lift_count INTEGER,
            base_elevation_m INTEGER,
            summit_elevation_m INTEGER,
            piste_km_by_difficulty_json TEXT,
            season_windows_json TEXT NOT NULL DEFAULT '[]',
            source_urls_json TEXT NOT NULL DEFAULT '[]'
        );

        CREATE TABLE IF NOT EXISTS stay_bases (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            resort_id TEXT NOT NULL REFERENCES resorts(resort_id) ON DELETE CASCADE,
            stay_base_id TEXT NOT NULL,
            name TEXT NOT NULL,
            price_range TEXT NOT NULL,
            price_min DOUBLE PRECISION NOT NULL,
            price_max DOUBLE PRECISION NOT NULL,
            quality TEXT NOT NULL,
            lift_distance TEXT NOT NULL,
            latitude DOUBLE PRECISION,
            longitude DOUBLE PRECISION,
            nearest_lift_name TEXT,
            nearest_lift_distance_m INTEGER,
            access_mode TEXT NOT NULL DEFAULT 'unknown',
            base_type TEXT,
            atmosphere_tags_json TEXT NOT NULL DEFAULT '[]',
            regional_data_ids_json TEXT NOT NULL DEFAULT '{}',
            CONSTRAINT stay_bases_stay_base_id_present_check
              CHECK (stay_base_id IS NOT NULL AND btrim(stay_base_id) <> '')
        );

        CREATE TABLE IF NOT EXISTS stay_base_skill_levels (
            stay_base_id INTEGER NOT NULL REFERENCES stay_bases(id) ON DELETE CASCADE,
            skill_level TEXT NOT NULL,
            PRIMARY KEY (stay_base_id, skill_level)
        );

        CREATE TABLE IF NOT EXISTS rentals (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            resort_id TEXT NOT NULL REFERENCES resorts(resort_id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            price_range TEXT NOT NULL,
            price_min DOUBLE PRECISION NOT NULL,
            price_max DOUBLE PRECISION NOT NULL,
            quality TEXT NOT NULL,
            lift_distance TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS resort_conditions (
            resort_id TEXT PRIMARY KEY
                REFERENCES ski_areas(ski_area_id) ON DELETE CASCADE,
            resort_name TEXT NOT NULL UNIQUE,
            snow_confidence_score DOUBLE PRECISION NOT NULL,
            snow_confidence_label TEXT NOT NULL,
            availability_status TEXT NOT NULL,
            weather_summary TEXT NOT NULL,
            conditions_score DOUBLE PRECISION NOT NULL,
            updated_at TEXT,
            source TEXT
        );

        CREATE TABLE IF NOT EXISTS resort_condition_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            resort_id TEXT NOT NULL REFERENCES ski_areas(ski_area_id) ON DELETE CASCADE,
            resort_name TEXT NOT NULL,
            observed_month INTEGER NOT NULL,
            observed_at TEXT NOT NULL,
            snow_confidence_score DOUBLE PRECISION NOT NULL,
            snow_confidence_label TEXT NOT NULL,
            availability_status TEXT NOT NULL,
            weather_summary TEXT NOT NULL,
            conditions_score DOUBLE PRECISION NOT NULL,
            source TEXT,
            UNIQUE(resort_id, observed_at)
        );

        CREATE TABLE IF NOT EXISTS raw_weather_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            resort_id TEXT NOT NULL REFERENCES ski_areas(ski_area_id) ON DELETE CASCADE,
            resort_name TEXT NOT NULL,
            elevation_band TEXT NOT NULL DEFAULT 'mid'
              CHECK (elevation_band IN ('base', 'mid', 'upper')),
            elevation_m INTEGER,
            observed_on DATE NOT NULL,
            observed_at TEXT NOT NULL,
            snowfall_cm DOUBLE PRECISION NOT NULL,
            snow_depth_m DOUBLE PRECISION,
            precipitation_sum_mm DOUBLE PRECISION,
            rain_sum_mm DOUBLE PRECISION,
            precipitation_hours DOUBLE PRECISION,
            snowfall_water_equivalent_sum_mm DOUBLE PRECISION,
            temperature_2m_max_c DOUBLE PRECISION NOT NULL,
            temperature_2m_min_c DOUBLE PRECISION NOT NULL,
            apparent_temperature_2m_max_c DOUBLE PRECISION,
            apparent_temperature_2m_min_c DOUBLE PRECISION,
            cloud_cover_mean_pct DOUBLE PRECISION,
            sunshine_duration_seconds DOUBLE PRECISION,
            visibility_min_m DOUBLE PRECISION,
            wind_speed_10m_max_kmh DOUBLE PRECISION NOT NULL,
            wind_gusts_10m_max_kmh DOUBLE PRECISION NOT NULL,
            weather_code INTEGER NOT NULL,
            record_type TEXT NOT NULL DEFAULT 'archive',
            source TEXT,
            source_model TEXT,
            CONSTRAINT raw_weather_history_resort_band_observed_source_key
            UNIQUE(resort_id, elevation_band, observed_on, source)
        );

        CREATE TABLE IF NOT EXISTS ski_area_snow_climatology_daily (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ski_area_id TEXT NOT NULL REFERENCES ski_areas(ski_area_id)
              ON DELETE CASCADE,
            resort_name TEXT NOT NULL,
            elevation_band TEXT NOT NULL
              CHECK (elevation_band IN ('base', 'mid', 'upper')),
            elevation_m INTEGER,
            month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
            day INTEGER NOT NULL CHECK (day BETWEEN 1 AND 31),
            baseline_period TEXT NOT NULL
              CHECK (baseline_period IN ('normal_30y', 'recent_15y')),
            baseline_start_year INTEGER NOT NULL,
            baseline_end_year INTEGER NOT NULL,
            evidence_seasons INTEGER NOT NULL CHECK (evidence_seasons >= 0),
            latest_archive_year INTEGER,
            snow_depth_cm_p25 DOUBLE PRECISION,
            snow_depth_cm_p50 DOUBLE PRECISION,
            snow_depth_cm_p75 DOUBLE PRECISION,
            prob_snow_depth_ge_30cm DOUBLE PRECISION NOT NULL
              CHECK (prob_snow_depth_ge_30cm BETWEEN 0 AND 1),
            prob_snow_depth_ge_50cm DOUBLE PRECISION NOT NULL
              CHECK (prob_snow_depth_ge_50cm BETWEEN 0 AND 1),
            avg_daily_snowfall_cm DOUBLE PRECISION NOT NULL,
            prob_rain_risk DOUBLE PRECISION NOT NULL
              CHECK (prob_rain_risk BETWEEN 0 AND 1),
            prob_freeze_thaw DOUBLE PRECISION NOT NULL
              CHECK (prob_freeze_thaw BETWEEN 0 AND 1),
            avg_max_temperature_c DOUBLE PRECISION NOT NULL,
            avg_wind_gust_kmh DOUBLE PRECISION NOT NULL,
            avg_snow_confidence_score DOUBLE PRECISION NOT NULL
              CHECK (avg_snow_confidence_score BETWEEN 0 AND 1),
            avg_conditions_score DOUBLE PRECISION NOT NULL
              CHECK (avg_conditions_score BETWEEN 0 AND 1),
            source_model TEXT NOT NULL,
            computed_at TEXT NOT NULL,
            CONSTRAINT ski_area_snow_climatology_daily_key
            UNIQUE (
                ski_area_id,
                elevation_band,
                month,
                day,
                baseline_period,
                source_model
            )
        );

        CREATE TABLE IF NOT EXISTS llm_parse_cache (
            cache_key TEXT PRIMARY KEY,
            query_text TEXT NOT NULL,
            model TEXT NOT NULL,
            prompt_version TEXT NOT NULL,
            schema_version TEXT NOT NULL,
            response_json TEXT NOT NULL,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS llm_narrative_cache (
            cache_key TEXT PRIMARY KEY,
            result_signature TEXT NOT NULL,
            model TEXT NOT NULL,
            prompt_version TEXT NOT NULL,
            schema_version TEXT NOT NULL,
            response_json TEXT NOT NULL,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS outbound_booking_clicks (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TEXT NOT NULL,
            resort_id TEXT NOT NULL REFERENCES resorts(resort_id) ON DELETE CASCADE,
            selected_area_name TEXT NOT NULL,
            selected_ski_area_name TEXT,
            target_url TEXT NOT NULL,
            source_surface TEXT NOT NULL,
            request_id TEXT,
            user_agent TEXT
        );

        CREATE TABLE IF NOT EXISTS app_users (
            user_id TEXT PRIMARY KEY,
            auth_provider TEXT NOT NULL,
            provider_subject TEXT NOT NULL,
            email TEXT NOT NULL,
            display_name TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            UNIQUE (auth_provider, provider_subject),
            UNIQUE (email)
        );

        CREATE TABLE IF NOT EXISTS auth_sessions (
            session_id TEXT PRIMARY KEY,
            user_id TEXT NOT NULL REFERENCES app_users(user_id) ON DELETE CASCADE,
            token_hash TEXT NOT NULL UNIQUE,
            created_at TEXT NOT NULL,
            expires_at TEXT NOT NULL,
            last_used_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS current_trip (
            singleton_id INTEGER PRIMARY KEY CHECK (singleton_id = 1),
            resort_id TEXT NOT NULL REFERENCES resorts(resort_id) ON DELETE CASCADE,
            resort_name TEXT NOT NULL,
            selected_area_name TEXT NOT NULL,
            selected_ski_area_id TEXT,
            selected_ski_area_name TEXT,
            travel_month INTEGER,
            trip_start_date DATE,
            trip_end_date DATE,
            booking_status TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_checked_at TEXT
        );

        CREATE TABLE IF NOT EXISTS user_current_trip (
            user_id TEXT PRIMARY KEY REFERENCES app_users(user_id) ON DELETE CASCADE,
            resort_id TEXT NOT NULL REFERENCES resorts(resort_id) ON DELETE CASCADE,
            resort_name TEXT NOT NULL,
            selected_area_name TEXT NOT NULL,
            selected_ski_area_id TEXT,
            selected_ski_area_name TEXT,
            travel_month INTEGER,
            trip_start_date DATE,
            trip_end_date DATE,
            booking_status TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_checked_at TEXT
        );

        CREATE TABLE IF NOT EXISTS user_devices (
            user_id TEXT NOT NULL REFERENCES app_users(user_id) ON DELETE CASCADE,
            installation_id TEXT NOT NULL,
            platform TEXT NOT NULL,
            push_token TEXT,
            push_enabled BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_seen_at TEXT NOT NULL,
            PRIMARY KEY (user_id, installation_id)
        );

        CREATE TABLE IF NOT EXISTS companion_events (
            event_id TEXT PRIMARY KEY,
            user_id TEXT NOT NULL REFERENCES app_users(user_id) ON DELETE CASCADE,
            resort_id TEXT NOT NULL REFERENCES resorts(resort_id) ON DELETE CASCADE,
            event_type TEXT NOT NULL,
            event_signature TEXT NOT NULL,
            actionable BOOLEAN NOT NULL,
            summary TEXT NOT NULL,
            changes_json TEXT NOT NULL,
            trip_window_status TEXT NOT NULL,
            conditions_updated_at TEXT,
            recorded_at TEXT NOT NULL,
            UNIQUE (user_id, event_signature)
        );
        """
    )
    _create_travel_cache_schema(connection)
    connection.execute(
        """
        ALTER TABLE resorts
        ADD COLUMN IF NOT EXISTS season_windows_json TEXT NOT NULL DEFAULT '[]'
        """
    )
    connection.execute(
        """
        ALTER TABLE resorts
        ADD COLUMN IF NOT EXISTS lift_pass_prices_json TEXT NOT NULL DEFAULT '[]'
        """
    )
    connection.execute(
        """
        ALTER TABLE resorts
        ADD COLUMN IF NOT EXISTS lift_pass_products_json TEXT NOT NULL DEFAULT '[]'
        """
    )
    connection.execute(
        """
        ALTER TABLE resorts
        ADD COLUMN IF NOT EXISTS terrain_groups_json TEXT NOT NULL DEFAULT '[]'
        """
    )
    connection.execute(
        """
        ALTER TABLE ski_areas
        ADD COLUMN IF NOT EXISTS season_windows_json TEXT NOT NULL DEFAULT '[]'
        """
    )
    connection.execute(
        """
        ALTER TABLE ski_areas
        ADD COLUMN IF NOT EXISTS total_piste_km DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS total_lift_count INTEGER,
        ADD COLUMN IF NOT EXISTS piste_km_by_difficulty_json TEXT
        """
    )
    connection.execute(
        """
        ALTER TABLE stay_bases
        ADD COLUMN IF NOT EXISTS stay_base_id TEXT,
        ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS nearest_lift_name TEXT,
        ADD COLUMN IF NOT EXISTS nearest_lift_distance_m INTEGER,
        ADD COLUMN IF NOT EXISTS access_mode TEXT NOT NULL DEFAULT 'unknown',
        ADD COLUMN IF NOT EXISTS base_type TEXT,
        ADD COLUMN IF NOT EXISTS atmosphere_tags_json TEXT NOT NULL DEFAULT '[]',
        ADD COLUMN IF NOT EXISTS regional_data_ids_json TEXT NOT NULL DEFAULT '{}'
        """
    )
    _backfill_stay_base_ids(connection)
    connection.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'stay_bases_stay_base_id_present_check'
          ) THEN
            ALTER TABLE stay_bases
            ADD CONSTRAINT stay_bases_stay_base_id_present_check
            CHECK (stay_base_id IS NOT NULL AND btrim(stay_base_id) <> '');
          END IF;
        END $$;
        """
    )
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS stay_bases_resort_stay_base_id_key
        ON stay_bases (resort_id, stay_base_id)
        """
    )
    connection.execute(
        """
        ALTER TABLE raw_weather_history
        ADD COLUMN IF NOT EXISTS record_type TEXT NOT NULL DEFAULT 'archive'
        """
    )
    connection.execute(
        """
        ALTER TABLE raw_weather_history
        ADD COLUMN IF NOT EXISTS elevation_band TEXT NOT NULL DEFAULT 'upper'
        """
    )
    connection.execute(
        """
        ALTER TABLE raw_weather_history
        ADD COLUMN IF NOT EXISTS elevation_m INTEGER
        """
    )
    connection.execute(
        """
        ALTER TABLE raw_weather_history
        ADD COLUMN IF NOT EXISTS precipitation_sum_mm DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS rain_sum_mm DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS precipitation_hours DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS snowfall_water_equivalent_sum_mm DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS apparent_temperature_2m_max_c DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS apparent_temperature_2m_min_c DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS cloud_cover_mean_pct DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS sunshine_duration_seconds DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS visibility_min_m DOUBLE PRECISION
        """
    )
    connection.execute(
        """
        UPDATE raw_weather_history AS history
        SET elevation_m = ski_areas.summit_elevation_m
        FROM ski_areas
        WHERE history.elevation_m IS NULL
          AND history.resort_id = ski_areas.ski_area_id
        """
    )
    connection.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'raw_weather_history_resort_id_observed_on_source_key'
          ) THEN
            ALTER TABLE raw_weather_history
            DROP CONSTRAINT raw_weather_history_resort_id_observed_on_source_key;
          END IF;
        END $$;
        """
    )
    connection.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'raw_weather_history_elevation_band_check'
          ) THEN
            ALTER TABLE raw_weather_history
            ADD CONSTRAINT raw_weather_history_elevation_band_check
            CHECK (elevation_band IN ('base', 'mid', 'upper'));
          END IF;
        END $$;
        """
    )
    connection.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'raw_weather_history_resort_band_observed_source_key'
          ) THEN
            ALTER TABLE raw_weather_history
            ADD CONSTRAINT raw_weather_history_resort_band_observed_source_key
            UNIQUE (resort_id, elevation_band, observed_on, source);
          END IF;
        END $$;
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS raw_weather_history_search_window_idx
        ON raw_weather_history (
            resort_id,
            elevation_band,
            record_type,
            observed_on
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS ski_area_snow_climatology_lookup_idx
        ON ski_area_snow_climatology_daily (
            ski_area_id,
            elevation_band,
            baseline_period,
            month,
            day
        )
        """
    )
    connection.execute(
        """
        ALTER TABLE current_trip
        ADD COLUMN IF NOT EXISTS trip_start_date DATE
        """
    )
    connection.execute(
        """
        ALTER TABLE current_trip
        ADD COLUMN IF NOT EXISTS trip_end_date DATE
        """
    )
    connection.execute(
        """
        ALTER TABLE user_current_trip
        ADD COLUMN IF NOT EXISTS trip_start_date DATE
        """
    )
    connection.execute(
        """
        ALTER TABLE user_current_trip
        ADD COLUMN IF NOT EXISTS trip_end_date DATE
        """
    )


def _create_travel_cache_schema(connection: psycopg.Connection[Any]) -> None:
    connection.execute(TRAVEL_CACHE_SCHEMA_SQL)


def _backfill_stay_base_ids(connection: psycopg.Connection[Any]) -> None:
    rows = connection.execute(
        """
        SELECT id, resort_id, name
        FROM stay_bases
        WHERE stay_base_id IS NULL OR btrim(stay_base_id) = ''
        ORDER BY id
        """
    ).fetchall()
    for row in rows:
        connection.execute(
            """
            UPDATE stay_bases
            SET stay_base_id = %s
            WHERE id = %s
            """,
            (_stable_stay_base_id(row["resort_id"], row["name"]), row["id"]),
        )


def _sync_resorts_from_seed(
    connection: psycopg.Connection[Any],
    resorts_path: Path,
) -> None:
    resorts = load_resorts_from_path(resorts_path)
    seeded_ids = sorted(resort.resort_id for resort in resorts)

    if seeded_ids:
        connection.execute(
            "DELETE FROM resorts WHERE NOT (resort_id = ANY(%s))",
            (seeded_ids,),
        )
    else:
        connection.execute("DELETE FROM resorts")

    for resort in resorts:
        connection.execute(
            """
            INSERT INTO resorts (
                resort_id,
                name,
                country,
                region,
                price_level,
                latitude,
                longitude,
                base_elevation_m,
                summit_elevation_m,
                season_start_month,
                season_end_month,
                season_windows_json,
                lift_pass_prices_json,
                lift_pass_products_json,
                terrain_groups_json
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (resort_id) DO UPDATE SET
                name = excluded.name,
                country = excluded.country,
                region = excluded.region,
                price_level = excluded.price_level,
                latitude = excluded.latitude,
                longitude = excluded.longitude,
                base_elevation_m = excluded.base_elevation_m,
                summit_elevation_m = excluded.summit_elevation_m,
                season_start_month = excluded.season_start_month,
                season_end_month = excluded.season_end_month,
                season_windows_json = excluded.season_windows_json,
                lift_pass_prices_json = excluded.lift_pass_prices_json,
                lift_pass_products_json = excluded.lift_pass_products_json,
                terrain_groups_json = excluded.terrain_groups_json
            """,
            (
                resort.resort_id,
                resort.name,
                resort.country,
                resort.region,
                resort.price_level,
                resort.latitude,
                resort.longitude,
                resort.base_elevation_m,
                resort.summit_elevation_m,
                resort.season_start_month,
                resort.season_end_month,
                _model_list_json(resort.season_windows),
                "[]",
                _model_list_json(resort.lift_pass_products),
                _model_list_json(resort.terrain_groups),
            ),
        )

        connection.execute(
            """
            DELETE FROM stay_base_skill_levels
            WHERE stay_base_id IN (
                SELECT id FROM stay_bases WHERE resort_id = %s
            )
            """,
            (resort.resort_id,),
        )
        connection.execute(
            "DELETE FROM stay_bases WHERE resort_id = %s",
            (resort.resort_id,),
        )
        connection.execute(
            "DELETE FROM rentals WHERE resort_id = %s",
            (resort.resort_id,),
        )

        current_ski_area_ids = [ski_area.ski_area_id for ski_area in resort.ski_areas]
        for ski_area in resort.ski_areas:
            connection.execute(
                """
                INSERT INTO ski_areas (
                    resort_id,
                    ski_area_id,
                    name,
                    latitude,
                    longitude,
                    base_elevation_m,
                    summit_elevation_m,
                    season_start_month,
                    season_end_month,
                    season_windows_json,
                    total_piste_km,
                    total_lift_count,
                    piste_km_by_difficulty_json
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                ON CONFLICT (ski_area_id) DO UPDATE SET
                    resort_id = excluded.resort_id,
                    name = excluded.name,
                    latitude = excluded.latitude,
                    longitude = excluded.longitude,
                    base_elevation_m = excluded.base_elevation_m,
                    summit_elevation_m = excluded.summit_elevation_m,
                    season_start_month = excluded.season_start_month,
                    season_end_month = excluded.season_end_month,
                    season_windows_json = excluded.season_windows_json,
                    total_piste_km = excluded.total_piste_km,
                    total_lift_count = excluded.total_lift_count,
                    piste_km_by_difficulty_json = excluded.piste_km_by_difficulty_json
                """,
                (
                    resort.resort_id,
                    ski_area.ski_area_id,
                    ski_area.name,
                    ski_area.latitude,
                    ski_area.longitude,
                    ski_area.base_elevation_m,
                    ski_area.summit_elevation_m,
                    ski_area.season_start_month,
                    ski_area.season_end_month,
                    _model_list_json(ski_area.season_windows),
                    ski_area.total_piste_km,
                    ski_area.total_lift_count,
                    _model_json(ski_area.piste_km_by_difficulty),
                ),
            )

        if current_ski_area_ids:
            connection.execute(
                """
                DELETE FROM ski_areas
                WHERE resort_id = %s AND NOT (ski_area_id = ANY(%s))
                """,
                (resort.resort_id, current_ski_area_ids),
            )
        else:
            connection.execute(
                "DELETE FROM ski_areas WHERE resort_id = %s",
                (resort.resort_id,),
            )

        for stay_base in resort.stay_bases:
            stay_base_row = connection.execute(
                """
                INSERT INTO stay_bases (
                    resort_id,
                    stay_base_id,
                    name,
                    price_range,
                    price_min,
                    price_max,
                    quality,
                    lift_distance,
                    latitude,
                    longitude,
                    nearest_lift_name,
                    nearest_lift_distance_m,
                    access_mode,
                    base_type,
                    atmosphere_tags_json,
                    regional_data_ids_json
                ) VALUES (
                    %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
                )
                RETURNING id
                """,
                (
                    resort.resort_id,
                    stay_base.stay_base_id,
                    stay_base.name,
                    stay_base.price_range,
                    stay_base.price_min,
                    stay_base.price_max,
                    stay_base.quality,
                    stay_base.lift_distance,
                    stay_base.latitude,
                    stay_base.longitude,
                    stay_base.nearest_lift_name,
                    stay_base.nearest_lift_distance_m,
                    stay_base.access_mode,
                    stay_base.base_type,
                    json.dumps(stay_base.atmosphere_tags, sort_keys=True),
                    json.dumps(stay_base.regional_data_ids, sort_keys=True),
                ),
            ).fetchone()
            assert stay_base_row is not None
            for skill_level in stay_base.supported_skill_levels:
                connection.execute(
                    """
                    INSERT INTO stay_base_skill_levels (stay_base_id, skill_level)
                    VALUES (%s, %s)
                    """,
                    (stay_base_row["id"], skill_level),
                )

        for rental in resort.rentals:
            connection.execute(
                """
                INSERT INTO rentals (
                    resort_id,
                    name,
                    price_range,
                    price_min,
                    price_max,
                    quality,
                    lift_distance
                ) VALUES (%s, %s, %s, %s, %s, %s, %s)
                """,
                (
                    resort.resort_id,
                    rental.name,
                    rental.price_range,
                    rental.price_min,
                    rental.price_max,
                    rental.quality,
                    rental.lift_distance,
                ),
            )


def _sync_terrain_domains_from_seed(
    connection: psycopg.Connection[Any],
    terrain_domains_path: Path | None,
) -> None:
    terrain_domains = (
        []
        if terrain_domains_path is None
        else load_terrain_domains_from_path(terrain_domains_path)
    )
    seeded_ids = sorted(
        terrain_domain.terrain_domain_id for terrain_domain in terrain_domains
    )

    if seeded_ids:
        connection.execute(
            "DELETE FROM terrain_domains WHERE NOT (terrain_domain_id = ANY(%s))",
            (seeded_ids,),
        )
    else:
        connection.execute("DELETE FROM terrain_domains")

    for terrain_domain in terrain_domains:
        connection.execute(
            """
            INSERT INTO terrain_domains (
                terrain_domain_id,
                name,
                ski_area_refs_json,
                metric_scope,
                total_piste_km,
                total_lift_count,
                base_elevation_m,
                summit_elevation_m,
                piste_km_by_difficulty_json,
                season_windows_json,
                source_urls_json
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (terrain_domain_id) DO UPDATE SET
                name = excluded.name,
                ski_area_refs_json = excluded.ski_area_refs_json,
                metric_scope = excluded.metric_scope,
                total_piste_km = excluded.total_piste_km,
                total_lift_count = excluded.total_lift_count,
                base_elevation_m = excluded.base_elevation_m,
                summit_elevation_m = excluded.summit_elevation_m,
                piste_km_by_difficulty_json = excluded.piste_km_by_difficulty_json,
                season_windows_json = excluded.season_windows_json,
                source_urls_json = excluded.source_urls_json
            """,
            (
                terrain_domain.terrain_domain_id,
                terrain_domain.name,
                _model_list_json(terrain_domain.ski_area_refs),
                terrain_domain.metric_scope,
                terrain_domain.total_piste_km,
                terrain_domain.total_lift_count,
                terrain_domain.base_elevation_m,
                terrain_domain.summit_elevation_m,
                _model_json(terrain_domain.piste_km_by_difficulty),
                _model_list_json(terrain_domain.season_windows),
                json.dumps(terrain_domain.source_urls, sort_keys=True),
            ),
        )


def _model_list_json(items: Any) -> str:
    return json.dumps(
        [item.model_dump(mode="json") for item in items],
        sort_keys=True,
    )


def _model_json(item: Any) -> str | None:
    if item is None:
        return None
    return json.dumps(item.model_dump(mode="json"), sort_keys=True)


def _clear_legacy_seeded_conditions(connection: psycopg.Connection[Any]) -> None:
    connection.execute("DELETE FROM resort_conditions WHERE source IS NULL")
