from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import psycopg
from psycopg.rows import dict_row

from app.config.env import load_dotenv_file

DATABASE_URL_ENV_VAR = "DATABASE_URL"
DEFAULT_DATABASE_URL = (
    "postgresql://planner:planner@127.0.0.1:5432/ai_sports_travel_planner"
)

TRAVEL_CACHE_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS travel_geocode_cache (
    normalized_origin TEXT NOT NULL,
    provider TEXT NOT NULL,
    resolved_label TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    fetched_at TEXT NOT NULL,
    PRIMARY KEY (normalized_origin, provider)
);

CREATE TABLE IF NOT EXISTS travel_route_cache (
    origin_key TEXT NOT NULL,
    destination_entity_type TEXT NOT NULL,
    destination_entity_id TEXT NOT NULL,
    destination_coord_key TEXT NOT NULL,
    mode TEXT NOT NULL,
    provider TEXT NOT NULL,
    distance_km DOUBLE PRECISION NOT NULL,
    duration_minutes INTEGER NOT NULL,
    provenance TEXT NOT NULL,
    fetched_at TEXT NOT NULL,
    PRIMARY KEY (
        origin_key,
        destination_entity_type,
        destination_entity_id,
        destination_coord_key,
        mode,
        provider
    )
);
"""


def resolve_database_url() -> str:
    load_dotenv_file()
    return os.getenv(DATABASE_URL_ENV_VAR, DEFAULT_DATABASE_URL)


def connect(
    database_url: str | None = None,
) -> psycopg.Connection[Any]:
    return psycopg.connect(database_url or resolve_database_url(), row_factory=dict_row)


def bootstrap_database(
    database_url: str | None = None,
    *,
    catalog_path: Path | None = None,
) -> None:
    from app.data.catalog_loader import CATALOG_PATH, load_catalog_from_path
    from app.data.catalog_sync import sync_catalog_snapshot

    snapshot = load_catalog_from_path(catalog_path or CATALOG_PATH)
    sync_catalog_snapshot(snapshot, database_url)


def reset_database(
    database_url: str | None = None,
    *,
    catalog_path: Path | None = None,
) -> None:
    with connect(database_url) as connection:
        connection.execute("DROP SCHEMA IF EXISTS public CASCADE")
        connection.execute("CREATE SCHEMA public")
    bootstrap_database(database_url, catalog_path=catalog_path)


def ensure_travel_cache_schema(database_url: str | None = None) -> None:
    with connect(database_url) as connection:
        _create_travel_cache_schema(connection)


def ensure_catalog_schema(database_url: str | None = None) -> None:
    with connect(database_url) as connection:
        _create_schema(connection)


def _create_schema(connection: psycopg.Connection[Any]) -> None:
    _remove_legacy_catalog_shape(connection)
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS ski_regions (
            ski_region_id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            grouping_policy TEXT NOT NULL,
            parent_ski_region_id TEXT REFERENCES ski_regions(ski_region_id)
                ON DELETE RESTRICT,
            source_urls_json TEXT NOT NULL DEFAULT '[]',
            is_active BOOLEAN NOT NULL DEFAULT TRUE
        );

        CREATE TABLE IF NOT EXISTS stay_destinations (
            stay_destination_id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            country TEXT NOT NULL,
            region TEXT NOT NULL,
            price_level TEXT NOT NULL,
            latitude DOUBLE PRECISION NOT NULL,
            longitude DOUBLE PRECISION NOT NULL,
            trip_market_region_id TEXT NOT NULL
                REFERENCES ski_regions(ski_region_id) ON DELETE RESTRICT,
            regional_data_ids_json TEXT NOT NULL DEFAULT '{}',
            is_active BOOLEAN NOT NULL DEFAULT TRUE
        );

        CREATE TABLE IF NOT EXISTS ski_areas (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ski_area_id TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            latitude DOUBLE PRECISION NOT NULL,
            longitude DOUBLE PRECISION NOT NULL,
            base_elevation_m INTEGER NOT NULL,
            summit_elevation_m INTEGER NOT NULL,
            season_start_month INTEGER NOT NULL,
            season_end_month INTEGER NOT NULL,
            season_windows_json TEXT NOT NULL DEFAULT '[]',
            total_piste_km DOUBLE PRECISION,
            total_lift_count INTEGER,
            piste_km_by_difficulty_json TEXT,
            supported_skill_levels_json TEXT NOT NULL DEFAULT '[]',
            snowmaking_json TEXT NOT NULL DEFAULT
                '{"availability":"unknown","coverage_pct":null,"coverage_basis":"unknown","season_label":null}',
            glacier_terrain_json TEXT NOT NULL DEFAULT
                '{"availability":"unknown"}',
            snow_park_json TEXT NOT NULL DEFAULT
                '{"availability":"unknown","park_count":null,"season_label":null}',
            night_skiing_json TEXT NOT NULL DEFAULT
                '{"availability":"unknown","season_label":null}',
            marked_freeride_routes_json TEXT NOT NULL DEFAULT
                '{"availability":"unknown","route_count":null,"season_label":null}',
            official_trail_map_json TEXT,
            ski_day_apres_profile_json TEXT NOT NULL DEFAULT
                '{"availability":"unknown","intensity":null,"season_label":null}',
            is_active BOOLEAN NOT NULL DEFAULT TRUE
        );

        CREATE TABLE IF NOT EXISTS terrain_domains (
            terrain_domain_id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            metric_scope TEXT NOT NULL,
            total_piste_km DOUBLE PRECISION,
            total_lift_count INTEGER,
            base_elevation_m INTEGER,
            summit_elevation_m INTEGER,
            piste_km_by_difficulty_json TEXT,
            season_windows_json TEXT NOT NULL DEFAULT '[]',
            source_urls_json TEXT NOT NULL DEFAULT '[]',
            official_trail_map_json TEXT,
            is_active BOOLEAN NOT NULL DEFAULT TRUE
        );

        CREATE TABLE IF NOT EXISTS stay_bases (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            stay_base_id TEXT NOT NULL UNIQUE,
            stay_destination_id TEXT NOT NULL
                REFERENCES stay_destinations(stay_destination_id)
                ON DELETE RESTRICT,
            name TEXT NOT NULL,
            price_range TEXT NOT NULL,
            price_min DOUBLE PRECISION NOT NULL,
            price_max DOUBLE PRECISION NOT NULL,
            quality TEXT NOT NULL,
            latitude DOUBLE PRECISION,
            longitude DOUBLE PRECISION,
            elevation_m INTEGER,
            base_type TEXT,
            regional_data_ids_json TEXT NOT NULL DEFAULT '{}',
            base_character_json TEXT NOT NULL DEFAULT
                '{"development_style":"unknown","local_pace":"unknown"}',
            local_apres_profile_json TEXT NOT NULL DEFAULT
                '{"availability":"unknown","intensity":null,"season_label":null}',
            is_active BOOLEAN NOT NULL DEFAULT TRUE
        );

        CREATE TABLE IF NOT EXISTS resort_conditions (
            ski_area_id TEXT PRIMARY KEY
                REFERENCES ski_areas(ski_area_id) ON DELETE RESTRICT,
            resort_name TEXT NOT NULL,
            snow_confidence_score DOUBLE PRECISION NOT NULL,
            snow_confidence_label TEXT NOT NULL,
            availability_status TEXT NOT NULL,
            weather_summary TEXT NOT NULL,
            conditions_score DOUBLE PRECISION NOT NULL,
            updated_at TEXT,
            source TEXT
        );

        CREATE TABLE IF NOT EXISTS resort_condition_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ski_area_id TEXT NOT NULL REFERENCES ski_areas(ski_area_id)
                ON DELETE RESTRICT,
            resort_name TEXT NOT NULL,
            observed_month INTEGER NOT NULL,
            observed_at TEXT NOT NULL,
            snow_confidence_score DOUBLE PRECISION NOT NULL,
            snow_confidence_label TEXT NOT NULL,
            availability_status TEXT NOT NULL,
            weather_summary TEXT NOT NULL,
            conditions_score DOUBLE PRECISION NOT NULL,
            source TEXT,
            CONSTRAINT resort_condition_history_ski_area_observed_at_key
            UNIQUE(ski_area_id, observed_at)
        );

        CREATE TABLE IF NOT EXISTS raw_weather_history (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ski_area_id TEXT NOT NULL REFERENCES ski_areas(ski_area_id)
                ON DELETE RESTRICT,
            resort_name TEXT NOT NULL,
            elevation_band TEXT NOT NULL DEFAULT 'mid'
              CHECK (elevation_band IN ('base', 'mid', 'upper')),
            elevation_m INTEGER,
            observed_on DATE NOT NULL,
            observed_at TEXT NOT NULL,
            snowfall_cm DOUBLE PRECISION NOT NULL,
            snow_depth_m DOUBLE PRECISION,
            precipitation_sum_mm DOUBLE PRECISION,
            rain_sum_mm DOUBLE PRECISION,
            precipitation_hours DOUBLE PRECISION,
            snowfall_water_equivalent_sum_mm DOUBLE PRECISION,
            temperature_2m_max_c DOUBLE PRECISION NOT NULL,
            temperature_2m_min_c DOUBLE PRECISION NOT NULL,
            apparent_temperature_2m_max_c DOUBLE PRECISION,
            apparent_temperature_2m_min_c DOUBLE PRECISION,
            cloud_cover_mean_pct DOUBLE PRECISION,
            sunshine_duration_seconds DOUBLE PRECISION,
            visibility_min_m DOUBLE PRECISION,
            wind_speed_10m_max_kmh DOUBLE PRECISION NOT NULL,
            wind_gusts_10m_max_kmh DOUBLE PRECISION NOT NULL,
            weather_code INTEGER NOT NULL,
            record_type TEXT NOT NULL DEFAULT 'archive',
            source TEXT,
            source_model TEXT,
            CONSTRAINT raw_weather_history_ski_area_band_observed_source_key
            UNIQUE(ski_area_id, elevation_band, observed_on, source)
        );

        CREATE TABLE IF NOT EXISTS ski_area_snow_climatology_daily (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ski_area_id TEXT NOT NULL REFERENCES ski_areas(ski_area_id)
              ON DELETE RESTRICT,
            resort_name TEXT NOT NULL,
            elevation_band TEXT NOT NULL
              CHECK (elevation_band IN ('base', 'mid', 'upper')),
            elevation_m INTEGER,
            month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
            day INTEGER NOT NULL CHECK (day BETWEEN 1 AND 31),
            baseline_period TEXT NOT NULL
              CHECK (baseline_period IN ('normal_30y', 'recent_15y')),
            baseline_start_year INTEGER NOT NULL,
            baseline_end_year INTEGER NOT NULL,
            evidence_seasons INTEGER NOT NULL CHECK (evidence_seasons >= 0),
            latest_archive_year INTEGER,
            snow_depth_cm_p25 DOUBLE PRECISION,
            snow_depth_cm_p50 DOUBLE PRECISION,
            snow_depth_cm_p75 DOUBLE PRECISION,
            prob_snow_depth_ge_30cm DOUBLE PRECISION NOT NULL
              CHECK (prob_snow_depth_ge_30cm BETWEEN 0 AND 1),
            prob_snow_depth_ge_50cm DOUBLE PRECISION NOT NULL
              CHECK (prob_snow_depth_ge_50cm BETWEEN 0 AND 1),
            avg_daily_snowfall_cm DOUBLE PRECISION NOT NULL,
            prob_rain_risk DOUBLE PRECISION NOT NULL
              CHECK (prob_rain_risk BETWEEN 0 AND 1),
            prob_freeze_thaw DOUBLE PRECISION NOT NULL
              CHECK (prob_freeze_thaw BETWEEN 0 AND 1),
            avg_max_temperature_c DOUBLE PRECISION NOT NULL,
            avg_wind_gust_kmh DOUBLE PRECISION NOT NULL,
            avg_snow_confidence_score DOUBLE PRECISION NOT NULL
              CHECK (avg_snow_confidence_score BETWEEN 0 AND 1),
            avg_conditions_score DOUBLE PRECISION NOT NULL
              CHECK (avg_conditions_score BETWEEN 0 AND 1),
            source_model TEXT NOT NULL,
            computed_at TEXT NOT NULL,
            CONSTRAINT ski_area_snow_climatology_daily_key
            UNIQUE (
                ski_area_id,
                elevation_band,
                month,
                day,
                baseline_period,
                source_model
            )
        );

        CREATE TABLE IF NOT EXISTS weather_forecast_runs (
            forecast_run_id TEXT PRIMARY KEY,
            forecast_source_key TEXT NOT NULL,
            provider_gateway TEXT NOT NULL,
            producer TEXT NOT NULL,
            provider_model_id TEXT NOT NULL,
            forecast_kind TEXT NOT NULL,
            model_initialization_time TIMESTAMPTZ NOT NULL,
            provider_availability_time TIMESTAMPTZ NOT NULL,
            ingested_at TIMESTAMPTZ NOT NULL,
            completed_at TIMESTAMPTZ,
            first_valid_date DATE NOT NULL,
            last_valid_date DATE NOT NULL,
            status TEXT NOT NULL
              CHECK (status IN ('building', 'complete', 'rejected', 'failed')),
            schema_version TEXT NOT NULL,
            parser_version TEXT NOT NULL,
            aggregation_policy_version TEXT NOT NULL,
            provider_metadata_json TEXT NOT NULL DEFAULT '{}',
            failure_reason TEXT,
            CHECK (last_valid_date >= first_valid_date),
            CHECK (
              (status = 'building' AND completed_at IS NULL
                AND failure_reason IS NULL)
              OR (status = 'complete' AND completed_at IS NOT NULL
                AND failure_reason IS NULL)
              OR (status IN ('rejected', 'failed') AND completed_at IS NOT NULL
                AND failure_reason IS NOT NULL)
            )
        );

        CREATE TABLE IF NOT EXISTS ski_area_weather_forecast_daily (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            forecast_run_id TEXT NOT NULL
              REFERENCES weather_forecast_runs(forecast_run_id)
              ON DELETE CASCADE,
            ski_area_id TEXT NOT NULL REFERENCES ski_areas(ski_area_id)
              ON DELETE RESTRICT,
            valid_local_date DATE NOT NULL,
            provider_timezone TEXT NOT NULL,
            elevation_band TEXT NOT NULL
              CHECK (elevation_band IN ('base', 'mid', 'upper')),
            representative_elevation_m INTEGER NOT NULL,
            request_latitude DOUBLE PRECISION NOT NULL,
            request_longitude DOUBLE PRECISION NOT NULL,
            snow_depth_cm DOUBLE PRECISION,
            snow_depth_spread_cm DOUBLE PRECISION,
            snowfall_cm DOUBLE PRECISION NOT NULL,
            rain_mm DOUBLE PRECISION NOT NULL,
            positive_degree_hours DOUBLE PRECISION NOT NULL,
            temperature_2m_min_c DOUBLE PRECISION NOT NULL,
            temperature_2m_max_c DOUBLE PRECISION NOT NULL,
            freezing_level_mean_m DOUBLE PRECISION,
            freezing_level_max_m DOUBLE PRECISION,
            wind_speed_10m_max_kmh DOUBLE PRECISION,
            wind_gusts_10m_max_kmh DOUBLE PRECISION,
            ensemble_member_count INTEGER,
            is_complete BOOLEAN NOT NULL,
            completeness_metadata_json TEXT NOT NULL DEFAULT '{}',
            CHECK (representative_elevation_m >= 0),
            CHECK (request_latitude BETWEEN -90 AND 90),
            CHECK (request_longitude BETWEEN -180 AND 180),
            CHECK (snow_depth_cm IS NULL OR snow_depth_cm >= 0),
            CHECK (
              snow_depth_spread_cm IS NULL OR snow_depth_spread_cm >= 0
            ),
            CHECK (snowfall_cm >= 0),
            CHECK (rain_mm >= 0),
            CHECK (positive_degree_hours >= 0),
            CHECK (temperature_2m_max_c >= temperature_2m_min_c),
            CHECK (
              ensemble_member_count IS NULL OR ensemble_member_count > 0
            ),
            CONSTRAINT ski_area_weather_forecast_daily_identity
              UNIQUE (
                forecast_run_id,
                ski_area_id,
                valid_local_date,
                elevation_band
              )
        );

        CREATE TABLE IF NOT EXISTS ski_area_forecast_heads (
            ski_area_id TEXT NOT NULL REFERENCES ski_areas(ski_area_id)
              ON DELETE RESTRICT,
            forecast_source_key TEXT NOT NULL,
            forecast_run_id TEXT NOT NULL
              REFERENCES weather_forecast_runs(forecast_run_id)
              ON DELETE RESTRICT,
            updated_at TIMESTAMPTZ NOT NULL,
            PRIMARY KEY (ski_area_id, forecast_source_key)
        );

        CREATE TABLE IF NOT EXISTS llm_parse_cache (
            cache_key TEXT PRIMARY KEY,
            query_text TEXT NOT NULL,
            model TEXT NOT NULL,
            prompt_version TEXT NOT NULL,
            schema_version TEXT NOT NULL,
            response_json TEXT NOT NULL,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS app_users (
            user_id TEXT PRIMARY KEY,
            auth_provider TEXT NOT NULL,
            provider_subject TEXT NOT NULL,
            email TEXT NOT NULL,
            display_name TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            UNIQUE (auth_provider, provider_subject),
            UNIQUE (email)
        );

        CREATE TABLE IF NOT EXISTS auth_sessions (
            session_id TEXT PRIMARY KEY,
            user_id TEXT NOT NULL REFERENCES app_users(user_id) ON DELETE CASCADE,
            token_hash TEXT NOT NULL UNIQUE,
            created_at TEXT NOT NULL,
            expires_at TEXT NOT NULL,
            last_used_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS user_devices (
            user_id TEXT NOT NULL REFERENCES app_users(user_id) ON DELETE CASCADE,
            installation_id TEXT NOT NULL,
            platform TEXT NOT NULL,
            push_token TEXT,
            push_enabled BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_seen_at TEXT NOT NULL,
            PRIMARY KEY (user_id, installation_id)
        );

        """
    )
    _create_travel_cache_schema(connection)
    connection.execute(
        """
        ALTER TABLE raw_weather_history
        ADD COLUMN IF NOT EXISTS record_type TEXT NOT NULL DEFAULT 'archive'
        """
    )
    connection.execute(
        """
        ALTER TABLE raw_weather_history
        ADD COLUMN IF NOT EXISTS elevation_band TEXT NOT NULL DEFAULT 'upper'
        """
    )
    connection.execute(
        """
        ALTER TABLE raw_weather_history
        ADD COLUMN IF NOT EXISTS elevation_m INTEGER
        """
    )
    connection.execute(
        """
        ALTER TABLE raw_weather_history
        ADD COLUMN IF NOT EXISTS precipitation_sum_mm DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS rain_sum_mm DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS precipitation_hours DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS snowfall_water_equivalent_sum_mm DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS apparent_temperature_2m_max_c DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS apparent_temperature_2m_min_c DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS cloud_cover_mean_pct DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS sunshine_duration_seconds DOUBLE PRECISION,
        ADD COLUMN IF NOT EXISTS visibility_min_m DOUBLE PRECISION
        """
    )
    connection.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'raw_weather_history_resort_id_observed_on_source_key'
          ) THEN
            ALTER TABLE raw_weather_history
            DROP CONSTRAINT raw_weather_history_resort_id_observed_on_source_key;
          END IF;
        END $$;
        """
    )
    connection.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'raw_weather_history_elevation_band_check'
          ) THEN
            ALTER TABLE raw_weather_history
            ADD CONSTRAINT raw_weather_history_elevation_band_check
            CHECK (elevation_band IN ('base', 'mid', 'upper'));
          END IF;
        END $$;
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS ski_area_snow_climatology_lookup_idx
        ON ski_area_snow_climatology_daily (
            ski_area_id,
            elevation_band,
            baseline_period,
            month,
            day
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS ski_area_weather_forecast_daily_lookup_idx
        ON ski_area_weather_forecast_daily (
            forecast_run_id,
            ski_area_id,
            valid_local_date,
            elevation_band
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS ski_area_forecast_heads_serving_idx
        ON ski_area_forecast_heads (
            ski_area_id,
            forecast_source_key,
            forecast_run_id
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS weather_forecast_runs_retention_idx
        ON weather_forecast_runs (
            status,
            model_initialization_time,
            forecast_source_key
        )
        """
    )
    _rename_resort_conditions_key_column(connection)
    _drop_resort_conditions_name_unique_constraint(connection)
    from app.data.catalog_schema import _ensure_normalized_catalog_schema

    _ensure_normalized_catalog_schema(connection)
    _ensure_normalized_outbound_booking_clicks(connection)
    _ensure_normalized_trip_tables(connection)


def _remove_legacy_catalog_shape(connection: psycopg.Connection[Any]) -> None:
    connection.execute("DROP TABLE IF EXISTS llm_narrative_cache")
    legacy_owner = connection.execute(
        """
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'ski_areas'
          AND column_name = 'resort_id'
        """
    ).fetchone()
    if legacy_owner is None:
        connection.execute("DROP TABLE IF EXISTS resorts CASCADE")
        connection.execute("DROP TABLE IF EXISTS rentals CASCADE")
        connection.execute("DROP TABLE IF EXISTS stay_base_skill_levels CASCADE")
        return

    connection.execute(
        """
        DROP TABLE IF EXISTS companion_events;
        DROP TABLE IF EXISTS user_current_trip;
        DROP TABLE IF EXISTS current_trip;
        DROP TABLE IF EXISTS outbound_booking_clicks;
        DROP TABLE IF EXISTS lift_pass_stay_destinations;
        DROP TABLE IF EXISTS lift_pass_terrain_domains;
        DROP TABLE IF EXISTS lift_pass_ski_areas;
        DROP TABLE IF EXISTS terrain_domain_ski_areas;
        DROP TABLE IF EXISTS ski_area_access;
        DROP TABLE IF EXISTS rental_display_facts;
        DROP TABLE IF EXISTS lift_pass_products;
        DROP TABLE IF EXISTS terrain_domains;
        DROP TABLE IF EXISTS stay_base_skill_levels;
        DROP TABLE IF EXISTS rentals;
        DROP TABLE IF EXISTS stay_bases;
        DROP TABLE IF EXISTS stay_destinations;
        DROP TABLE IF EXISTS ski_regions;
        ALTER TABLE ski_areas DROP COLUMN resort_id CASCADE;
        DROP TABLE IF EXISTS resorts CASCADE;
        """
    )


def _ensure_normalized_outbound_booking_clicks(
    connection: psycopg.Connection[Any],
) -> None:
    columns = {
        row["column_name"]
        for row in connection.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'outbound_booking_clicks'
            """
        ).fetchall()
    }
    if columns and "stay_destination_id" not in columns:
        connection.execute("DROP TABLE outbound_booking_clicks")
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS outbound_booking_clicks (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TEXT NOT NULL,
            stay_destination_id TEXT NOT NULL
                REFERENCES stay_destinations(stay_destination_id)
                ON DELETE RESTRICT,
            stay_base_id TEXT NOT NULL
                REFERENCES stay_bases(stay_base_id) ON DELETE RESTRICT,
            focus_ski_area_id TEXT NOT NULL
                REFERENCES ski_areas(ski_area_id) ON DELETE RESTRICT,
            target_url TEXT NOT NULL,
            source_surface TEXT NOT NULL,
            request_id TEXT,
            user_agent TEXT
        )
        """
    )


def _ensure_normalized_trip_tables(connection: psycopg.Connection[Any]) -> None:
    current_columns = {
        row["column_name"]
        for row in connection.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'user_current_trip'
            """
        ).fetchall()
    }
    if current_columns and "ski_region_id" not in current_columns:
        connection.execute(
            """
            DROP TABLE IF EXISTS companion_events;
            DROP TABLE IF EXISTS user_current_trip;
            DROP TABLE IF EXISTS current_trip;
            """
        )
    else:
        connection.execute("DROP TABLE IF EXISTS current_trip")

    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS user_current_trip (
            user_id TEXT PRIMARY KEY
                REFERENCES app_users(user_id) ON DELETE CASCADE,
            ski_region_id TEXT NOT NULL
                REFERENCES ski_regions(ski_region_id) ON DELETE RESTRICT,
            ski_region_name TEXT NOT NULL,
            stay_destination_id TEXT NOT NULL
                REFERENCES stay_destinations(stay_destination_id)
                ON DELETE RESTRICT,
            stay_destination_name TEXT NOT NULL,
            stay_base_id TEXT NOT NULL
                REFERENCES stay_bases(stay_base_id) ON DELETE RESTRICT,
            stay_base_name TEXT NOT NULL,
            focus_ski_area_id TEXT NOT NULL
                REFERENCES ski_areas(ski_area_id) ON DELETE RESTRICT,
            focus_ski_area_name TEXT NOT NULL,
            lift_pass_product_id TEXT NOT NULL
                REFERENCES lift_pass_products(lift_pass_product_id)
                ON DELETE RESTRICT,
            lift_pass_product_name TEXT NOT NULL,
            travel_month INTEGER,
            trip_start_date DATE,
            trip_end_date DATE,
            booking_status TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_checked_at TEXT
        );

        CREATE TABLE IF NOT EXISTS companion_events (
            event_id TEXT PRIMARY KEY,
            user_id TEXT NOT NULL
                REFERENCES app_users(user_id) ON DELETE CASCADE,
            ski_region_id TEXT NOT NULL
                REFERENCES ski_regions(ski_region_id) ON DELETE RESTRICT,
            stay_destination_id TEXT NOT NULL
                REFERENCES stay_destinations(stay_destination_id)
                ON DELETE RESTRICT,
            stay_base_id TEXT NOT NULL
                REFERENCES stay_bases(stay_base_id) ON DELETE RESTRICT,
            focus_ski_area_id TEXT NOT NULL
                REFERENCES ski_areas(ski_area_id) ON DELETE RESTRICT,
            lift_pass_product_id TEXT NOT NULL
                REFERENCES lift_pass_products(lift_pass_product_id)
                ON DELETE RESTRICT,
            event_type TEXT NOT NULL,
            event_signature TEXT NOT NULL,
            actionable BOOLEAN NOT NULL,
            summary TEXT NOT NULL,
            changes_json TEXT NOT NULL,
            trip_window_status TEXT NOT NULL,
            conditions_updated_at TEXT,
            recorded_at TEXT NOT NULL,
            UNIQUE (user_id, event_signature)
        );
        """
    )


def _create_travel_cache_schema(connection: psycopg.Connection[Any]) -> None:
    connection.execute(TRAVEL_CACHE_SCHEMA_SQL)


def _rename_resort_conditions_key_column(
    connection: psycopg.Connection[Any],
) -> None:
    connection.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'resort_conditions'
              AND column_name = 'resort_id'
          ) AND NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'resort_conditions'
              AND column_name = 'ski_area_id'
          ) THEN
            ALTER TABLE resort_conditions
            RENAME COLUMN resort_id TO ski_area_id;
          END IF;
        END $$;
        """
    )


def _drop_resort_conditions_name_unique_constraint(
    connection: psycopg.Connection[Any],
) -> None:
    connection.execute(
        """
        DO $$
        DECLARE
          constraint_name text;
        BEGIN
          SELECT con.conname
          INTO constraint_name
          FROM pg_constraint con
          JOIN pg_class rel ON rel.oid = con.conrelid
          JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
          WHERE rel.relname = 'resort_conditions'
            AND nsp.nspname = current_schema()
            AND con.contype = 'u'
            AND (
              SELECT array_agg(att.attname::text ORDER BY ord.ordinality)
              FROM unnest(con.conkey) WITH ORDINALITY AS ord(attnum, ordinality)
              JOIN pg_attribute att
                ON att.attrelid = con.conrelid
               AND att.attnum = ord.attnum
            ) = ARRAY['resort_name'];

          IF constraint_name IS NOT NULL THEN
            EXECUTE format(
              'ALTER TABLE resort_conditions DROP CONSTRAINT %I',
              constraint_name
            );
          END IF;
        END $$;
        """
    )
